			<!--Include Header-->
            <?php
                require('../_includes/nxtconfig.php');
                include('../_includes/dbconfig.php');
               include('../_includes/mailsend.php');
               require('razorpay-php/Razorpay.php');
               $cust_id = $_GET["cust_id"];
               $pid = $_GET["plan_id"];
               $con = mysqli_connect(HOST,USER,PASS,DB) or die('Unable to Connect...');
               use Razorpay\Api\Api;
			   use Razorpay\Api\Errors\SignatureVerificationError;
			   $api = new Api($keyId, $keySecret);
			   $error_reason = 0;
			?>
	 
<body onload="document.frm1.submit()"> 
	 		 <?php
			   $commission = 1;
			   $mail_res = 1; 
			   $action = "success.php";
			   $current_dt = date("Y-m-d");
			   //update customer to actve
			    $q = "UPDATE  `tb_customers_plan` SET  `active` = 1,entry_date = '$current_dt'  WHERE `cust_id` = '$cust_id' AND `plan_id`=$pid ";
			    $r = mysqli_query($con, $q);
			    if (!$r) 
			    {
			    	$error_reason = 2;
			        echo("Error in Updation: " . mysqli_error($con));

			    } 
			   

               //For mail sending
			  $query="SELECT email_id,phone_no,business_counselor,trans_no,plan_id,category_id FROM tb_customers,tb_customers_plan,tb_customers_business WHERE  `tb_customers_plan`.`cust_id` =`tb_customers`.`id` AND `tb_customers_business`.`customer_id` =`tb_customers`.`id` AND`tb_customers`.id ='$cust_id'";


				  $r = mysqli_query($con, $query);
				  if ($row = mysqli_fetch_array($r))
				  {
				      $email_id = $row['email_id']; 
				      $phone_no = $row['phone_no'];
				      $bus_counselor = $row['business_counselor'];
				      $trans_no = $row['trans_no'];
				      $plan = $row['plan_id'];
				      $category = $row['category_id'];
				  } 
			  	
			 $mail_res = mailsend($email_id,$email_id,$phone_no);
			 
			//business counseleor Settlement
			if($bus_counselor != "")
  			{
				 $b_q ="SELECT email_id,raz_account_id FROM tb_bussiness_counsellors WHERE id ='$bus_counselor'";
	      

		        $b_r = mysqli_query($con, $b_q);
		        if ($b_row = mysqli_fetch_array($b_r))
		        {
		            $bus_email = $b_row['email_id']; 
		            $accountId = $b_row['raz_account_id'];
		            echo "BC =". $accountId;
		            
		        } 
		        //getting commission Amount
		        $b_c = "SELECT amount FROM  `tb_bc_comm_setting` WHERE plan_id = $plan AND category = $category ";
		        $b_r = mysqli_query($con, $b_c);
		        if ($b_row = mysqli_fetch_array($b_r))
		        {
		           $com_amt = $b_row['amount']; 
		           $razor_amt = $com_amt *100;
		            
		        } 
				//transfer commission Amount
	      		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
				$ch = curl_init();

				curl_setopt($ch, CURLOPT_URL, 'https://api.razorpay.com/v1/transfers');
				curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
				curl_setopt($ch, CURLOPT_POST, 1);
				curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\t\t  \"account\": \"".$accountId."\",\n\t\t  \"amount\":$razor_amt,\n\t\t  \"currency\": \"INR\"\n\t}");
				curl_setopt($ch, CURLOPT_USERPWD, 'rzp_test_II9DJCFzOS6c4U' . ':' . 'EaBsjAazwwJbPvvvavpnINY4');

				$headers = array();
				$headers[] = 'Content-Type: application/json';
				curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

				$result = curl_exec($ch);
				if (curl_errno($ch)) {
					$action = "error-cust-payment.php";
                	$error_reason = 3;
				    //echo 'Error:' . curl_error($ch);
				}
				else
				{
					 //store commission Amount
					 $q1 = "INSERT INTO tb_bc_comm_amount(bc_id,trans_no,amount) VALUES ('$bus_counselor',$trans_no,$com_amt)";
			               
			        $r1 = mysqli_query($con, $q1);
			        if(!$r1)
			        {
			        	 $action = "error-cust-payment.php";
                		 $error_reason = 3;

			        }

				}
				curl_close($ch);
		  
		 	}
            ?>
            <form action='<?php echo $action; ?>' name="frm1" method="post">
	           <input type="hidden" value='<?php echo $commission; ?>' name="commission">
	           <input type="hidden" value='<?php echo $mail_res; ?>' name="mail_res">
              </form>
</body>
		      
            